### ISSUE TITLE
Display logging metadata in console depending on a flag

### ISSUE THREAD

**Issue by gelim92** [GovTechSG/mcf-boilerplate-js#37]
Currently the metadata from logger error messages are not displayed in the developer console. Would be nice if we could display this data in the console if `NODE_ENV === 'development'` to help with debugging.

**Comment by Nebulis** [comment]
While I think a flag could be useful, I'm not sure whether checking on `NODE_ENV === 'development'`

My main concern is that it will make logs really verbose by default as metadata can contain a lot of information

**Comment by gelim92** [comment]
Agree with creating a separate flag 👍 

Maybe `LOG_VERBOSE` ?

**Comment by Neurrone** [comment]
This is fixed now, profile and job now shows metadata in development
