### ISSUE TITLE
Unnecessary use of lodash remove() in @mcf/constants

### ISSUE THREAD

**Issue by zephinzer** [GovTechSG/mcf-boilerplate-js#66]
Referencing: https://github.com/GovTechSG/mcf-boilerplate-js/blob/100ab62f7d68191e74c8c4164a9f8188e42ea275/packages/constants/src/mcf.ts#L642

We could use the native `.filter(word => !STOP_WORDS.includes(word))` instead?

**Comment by EmixamE** [comment]
updated
